name: YCAI - Pull Request

on:
  pull_request:
    branches:
      - daily
      - beta
    paths:
      - "shared/**"
      - "YCAI/**"

defaults:
  run:
    working-directory: YCAI

jobs:
  pull_request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.2']
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          mongodb-db: test

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::~/.npm"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install shared modules
        working-directory: shared
        run: npm i

      - name: Install YCAI modules
        run: npm i

      - name: Lint code
        run: npm run lint

      - name: Build shared
        working-directory: ./shared
        run: npm run build

      - name: Build dashboard
        run: npm run build

      - name: Build extension for tests
        run: npm run build:ext:dev

      - name: Test spec
        run: npm test spec

      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: test

      - name: Start api service
        working-directory: ./backend
        run: nohup npm run start --key ci-key

      - name: Test Code
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: true
        with:
          args: npm test e2e -- --watchAll=false
